### ISSUE TITLE
Subtle bug regarding context

### ISSUE THREAD

**Issue by mcjazzyfunky** [dyo/dyo#102]
Please have a look at the following working React demo:
https://codesandbox.io/s/floral-resonance-p6upg

A Dyo version of the above demo looks like this but this is not working - please open with Firefox as Dyo seems to get into some kind of endless loop, so Firefox suggests after a while to stop the script:
https://codesandbox.io/s/sharp-satoshi-z05cv

**Comment by mcjazzyfunky** [comment]
Thanks @thysultan - that bug seems to be fixed now.

But something else is strange:

Please compare the behavior of this React demo:
https://codesandbox.io/s/floral-resonance-p6upg

with the behavior of this Dyo demo:
https://codesandbox.io/s/dreamy-shape-42nqv

That "Last update" value should not update, but it is updating each second in Dyo.
Above I've said "strange", because I am using similar demos in two other scenarios and everything seems to work perfectly fine there after the upgrade to dyo@1.0.1.

**Comment by thysultan** [comment]
When you say strange does the same thing work outside of codesandbox?

**Comment by thysultan** [comment]
It works outside of codesandbox on my local machine.

**Comment by mcjazzyfunky** [comment]
You're right ... this issue only exists in codesandbox.

For example the same code is working perfectly fine here:
https://jsfiddle.net/8rkqamp1/

🤔
