### ISSUE TITLE
The functions of Dyo.Children are not working properly

### ISSUE THREAD

**Issue by mcjazzyfunky** [dyo/dyo#103]
Please compare the console output of the following two demos:

With React (everything working as expected):
~https://jsfiddle.net/xf7Lkpom~ (Edit - fixed: https://jsfiddle.net/hfrvnmjL)

With Dyo (not working as expected):
~https://jsfiddle.net/o052hcwk~ (Edit -fixed: https://jsfiddle.net/Ltqzkue3)

**Comment by thysultan** [comment]
It should be `elem.children` not `elem.props.children`, the later is only true for components.

**Comment by mcjazzyfunky** [comment]
Oops, my bad.
Please check the following corrected Dyo demo and have a look at the console output:
https://jsfiddle.net/tnf3d1x6

... and compare to the output to its React counterpart.
https://jsfiddle.net/xf7Lkpom

Maybe this behavior is what is intended but Dyo's `Children` helper function do NOT flatten the children as this is done in React `Children` and Preact's `toChildArrray`. But isn't a "flattening" version much more useful?

**Comment by mcjazzyfunky** [comment]
Oops, my bad ... I will correct the demo ... to be continued...

**Comment by mcjazzyfunky** [comment]
Oops, my bad ... I have fixed the above demos:

React:
https://jsfiddle.net/hfrvnmjL/

Dyo:
https://jsfiddle.net/Ltqzkue3/

**Comment by mcjazzyfunky** [comment]
@thysultan TYVM for that bugfix. I've tested it and it's seems to work fine now.
