### ISSUE TITLE
Feature request: Support for children of type object where `valueOf()` returns a renderable value

### ISSUE THREAD

**Issue by mcjazzyfunky** [dyo/dyo#104]
Currently, if an object `obj`  is neither an iterable nor a virtual element it will not be rendered when used in `<div>{obj}</div>`.

Would it be possible to allow `obj` to be rendered if its `valueOf` method returns something renderable?
Use case is that you have values that are wrapped in some special objects and unwrapping could be done automatically in JSX, which would syntactically be much nicer (Sultan, if I remember correctly this was even your own suggestion in some older React discussion thread).

`<div>{obj}</div>` instead for example `<div>{obj.value}</div>`

**Comment by Zolmeister** [comment]
Out of curiosity, what would it take to make `obj` an instanceof `virtual element`?

**Comment by mcjazzyfunky** [comment]
Actually, in my use case it only needs `obj.value` to convert to some renderable value.
But the problem is, you have to do this over and over again - what would be a real show-stopper if someone really needs this.
In my particular case it's just about a litte fun project based on Dyo where I noodle around with some alternatives APIs to implement components.
For example here's a little demo (I think it's obvious that I've tried to find some API where there are no closures in the render function etc.)
https://codesandbox.io/s/gifted-napier-ovhk8
The variables `$count`, `$locale`, `$mouseX` and `$mouseY` are all of type `{ value: T }` (=> property `value` will change over time), nevertheless I never had to write `xxx.value` explicitly. This is at the moment not possible in Dyo out of the box. And implementing this in userland (like I have done) would have a bad impact on the performance of `createElement`.

**Comment by thysultan** [comment]
obj cannot from outside be an instance of `virtual element`. 

I suppose, this(delegating to valueOf) should be safe – right now we just no-op unknown values.

**Comment by mcjazzyfunky** [comment]
I think I've changed my mind and will withdraw that feature request for now as it is just a randomly used edge case. Maybe I'll asked again somewhere in future, but for now this feature may not be that important.
