### ISSUE TITLE
Async generator return value as result tree

### ISSUE THREAD

**Issue by Zolmeister** [dyo/dyo#112]
It looks like the return value for async generator components is being skipped

```coffee
Root = ->
  yield await Promise.resolve null
  # yield h 'div', 'abc'
  return h 'div', 'abc'
```
```
Expected: <div>abc</div>
Received: 
```

**Comment by thysultan** [comment]
When you have 

```js
async function* Root (props) {
  yield await Promise.resolve(null)
  yield await h('div', {}, 'abc')
}
```

We get the value from the generator: `{value: undefined, done: true}` that is equally true for

```js
async function* Root (props) {
  yield await Promise.resolve(null)
  return h('div', {}, 'abc')
}
```

Where we get `{value: element, done: true}`, the question then arises should carry over to the first example? i.e render the return value `undefined`.

**Comment by thysultan** [comment]
Reference document: the [iterator protocol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators)

**Comment by Zolmeister** [comment]
Yes, I guess that would be a breaking change.
I think rendering `undefined` for your first example makes sense.

non-async generators are not affected because of concatenation `[element, undefined]`

**Comment by thysultan** [comment]
I'm not so much worried about it being a breaking change, but more a semantic divergence. The iterator protocol doesn't establish precedence for consuming the iterator value after the `done` signal has been established. Do you have any examples where this is not the case?

**Comment by Zolmeister** [comment]
From MDN: `If value is present alongside done, it is the iterator's return value`

**Comment by Zolmeister** [comment]
I see what you mean

```js
function* x() { yield 1; yield 2; return 3}
for (v of x()) { console.log(v) }
```
produces
```
1, 2, undefined
```
instead of 
```
1, 2, 3
```

However the docs clearly define return-value behavior, so I would  say it's fine. Especially since  we are using generators here for control-flow and not to produce results.

**Comment by Zolmeister** [comment]
I no longer need this functionality (see #113). Feel free to re-open if you still think this would be a valuable change.
