### ISSUE TITLE
why use rAF of useEffect but not setTimeout

### ISSUE THREAD

**Issue by yisar** [dyo/dyo#118]
In fact, useEffect will run until after-paint, but requestAnimationFrame will ru你before it, so can you tell me why use requestAnimationFrame ? where is the better than setTimeout?
Thank you very much.

**Comment by thysultan** [comment]
useEffect will happen after layout but before paint in dyo, this can change in the future: I think React uses requestionAnimationFrame and postMessage*, what did you opt to use in fre?

**Comment by yisar** [comment]
I use Message Channel in fre, which is equivalent to setTimeout, but it does not waste at least 4ms of time.
[here](https://github.com/yisar/fre/blob/master/src/scheduler.js#L56)

As far as I know, requestAnimationFrame will be paused when running in background tabs, 
but I don't know weather it is a drawback or not.

**Comment by thysultan** [comment]
If you want to execute after "paint" wouldn't you still need to invoke the Message Channel within a requestAnimationFrame?

**Comment by yisar** [comment]
@thysultan https://github.com/yisar/fre/blob/master/src/scheduler.js#L56

I have modified it. Now it uses the requestAnimationFrame, too. 
But I don't have a good reason. It's probably the closest to react. What do you think?

**Comment by thysultan** [comment]
I was thinking more along the lines of:

```js
requestAnimationFrame(() => port2.postMessage(null))
```

**Comment by yisar** [comment]
@thysultan https://github.com/dyo/dyo/issues/124 From this issue, using the requestanimationframe is just fine.

To be honest, I'm not sure when the effect will be execute. Maybe we need a good summary.
