### ISSUE TITLE
Exception message not a string

### ISSUE THREAD

**Issue by Zolmeister** [dyo/dyo#122]
As per docs https://dyo.js.org/top-level.html#Boundary fallback error message should be a `string`

```coffee
Child = ->
  throw new Error 'xxx'

Root = ->
  h Boundary,
    fallback: (err) ->
      console.log typeof err.message
    h 'div', Child
```

Expected
```
string
```
Received
```
object
```

https://github.com/dyo/dyo/pull/120#issuecomment-559702451

**Comment by thysultan** [comment]
That is expected: the message type is whatever the type of the error that is thrown is i.e `throw 1` will yield a `number` message.

**Comment by Zolmeister** [comment]
Oh, I see the docs were updated. Not sure I agree with it (I think the original error would suffice), but oh well
