### ISSUE TITLE
child-array re-use error

### ISSUE THREAD

**Issue by Zolmeister** [dyo/dyo#125]
https://codesandbox.io/s/jolly-mahavira-s0ijz

```coffee
Ripple = ->
  [$waves, setWaves] = useState []

  ripple = useCallback ->
    $wave =  h 'div'
    setWaves $waves.concat $wave
    window.requestAnimationFrame ->
      setWaves _.without $waves, $wave
  , [$waves]

  h 'div',
    className: 'ripple'
    onmousedown: ripple
    $waves

$el = document.createElement 'div'
render Ripple, $el
$ripple = $el.querySelector '.ripple'
$ripple.dispatchEvent new Event 'mousedown'
# The second dispatch tirggers the error
$ripple.dispatchEvent new Event 'mousedown'
```

Exception

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

**Comment by thysultan** [comment]
This probably has nothing to do with race conditions or useCallback and more with holding onto references of the `virtual nodes` instead of using a declarative approach.

i.e

```
Ripple = ->
  [$waves, setWaves] = useState []

  ripple = useCallback ->
    $wave =  [Math.random()]
    setWaves $waves.concat $wave
    window.requestAnimationFrame ->
      setWaves _.without $waves, $wave
  , [$waves.map(v => h('div', {}, v))]

  h 'div',
    className: 'ripple'
    onmousedown: ripple
    $waves
```

**Comment by thysultan** [comment]
This is expected.

**Comment by Zolmeister** [comment]
@thysultan How so? This worked in dio v8

**Comment by thysultan** [comment]
Yes, that was one of the breaking changes from v8 -> v9, which carried over to dyo. It wasn't worth the complexity to support it since it's not idiomatic to the declarative paradigm.

**Comment by Zolmeister** [comment]
@thysultan can this be easily detected and produce a better error message?

**Comment by thysultan** [comment]
Looking at this closer: the following also resolves this issue:

```coffee
  h 'div',
    className: 'ripple'
    onmousedown: ripple,
    [...$waves], 'or', ...$waves
```

**Comment by thysultan** [comment]
If we change: https://github.com/dyo/dyo/blob/master/src/Element.js#L137 to 

```js
return iterable(value.concat(null), hash(index))
```

It should solve that issue. Current code reuses(direct assignment) the array which avoids creating a new array but concat could be just as fast/negligible.

**Comment by Zolmeister** [comment]
Great
Also `value.concat(null)` appends a null (not sure if it matters). Use `value.concat()` instead.

**Comment by thysultan** [comment]
>not sure if it matters

The append a `null` part is deliberate.

**Comment by Zolmeister** [comment]
Why append null?

**Comment by thysultan** [comment]
Similar reason as to why we append `empty` in the current instalment https://github.com/dyo/dyo/blob/master/src/Element.js#L137 it acts as an anchor node for the fragment, and arrays act like fragments in order to be afforded a certain level of isolation from siblings, this can avoid key collision under certain conditions i.e in

```js
h(div, {}, [h('h1', {key: 1}, 1)], [h('h1', {key: 1}, 1)])
```

Both heading are under separate namespaces(arrays) so can reuse the same key, this is more useful when you are using something like 

```js
h('div', {}, 
   arr1.map(v => h('h1', {key: v.id}, v.data)),
   arr2.map(v => h('h1', {key: v.id}, v.data))
)
```

...and not have to worry whether `v.id` in the two data source will collide.

I put `null` instead of `empty()` because they are effectively represent they same type of node vice-versa.

**Comment by thysultan** [comment]
Better comparison of current(push) vs the proposed(concat): https://jsperf.com/concat-vs-inline-push

**Comment by Zolmeister** [comment]
Perhaps running a more realistic benchmark would help understand the impact.
e.g. https://github.com/krausest/js-framework-benchmark

From a correctness standpoint I think mutation should be avoided.
Could you anchor the fragment by polluting it's properties instead?

**Comment by thysultan** [comment]
Yes, testing the whole `h/createElement` function variants would be the better comparison.
