### ISSUE TITLE
About immutable virtual elements

### ISSUE THREAD

**Issue by mcjazzyfunky** [dyo/dyo#130]
@thysultan This is just a question: Virtual elments in Dyo are not immutable (in contrast to e.g. React or ivi). Would it theoretically be possible in future Dyo versions to switch to immutable virtual elements without significantly losing performance or is performance the main reason why Dyo uses mutating virutal elements in the first place?

**Comment by thysultan** [comment]
It is possible, for example IvI made a similar move from mutable to immutable(unsure if that is still the case).

**Comment by mcjazzyfunky** [comment]
Okay, good to hear, because sometimes there are seldom use-cases where immutable VNodes would help.
