### ISSUE TITLE
Better support for custom elements

### ISSUE THREAD

**Issue by mcjazzyfunky** [dyo/dyo#132]
Dyo's support for custom elements could actually be a bit better.

Please have a look at the following demo:
https://codesandbox.io/s/hopeful-sound-l3bvo?file=/src/index.js

You find there two custom elements `<custom-element ...>` and `<haunted-custom-element ...>`.
While the first one is implemented without using a special library, the second one is using the "haunted" web component library. It's important to know that "haunted" uses a proxy to handle the custom element's properties (no special setter or getter property functions are used).

The demo uses Preact and I would say this is working as expected: It seems that if Preact finds a defined property it will use this property for setting the new value otherwise it will use `setAttribute`.
As "Haunted" uses a proxy instead of explicitly defined props the Preact's heuristic fails. But I think that's not Preact fault, using a proxy for the custom elements may just not be the best solution.

If you switch the demo to "Dyo" then the output is quite different: It seems that only `setAttribute` is used in this demo.

Any chance that this could be enhanced some day (I don't think that this is urgent)?

**Comment by thysultan** [comment]
If you change:

```js
this._a = undefined
this._b = undefined
this._c = undefined
```

To use `null` instead of `undefined`, it should work.

Dyo assumes undefined to mean no property exists. Normal DOM nodes use `null` in the place of undefined for un-defined values

**Comment by mcjazzyfunky** [comment]
Ah okay, very interesting, thanks. In fact I was extremely confused: A couple of weeks ago I've tested the web component support of Dyo and was delighted how well everything was working. Then yesterday I had a case very only one property was working fine and the other was completely ignored. Then in this little demo above strangely nothing was really working as expected. Now I know the reason why.
Would it mean a significant performance loss if we use `hasOwnProperty` instead?
Or is the special rule that in custom elements properties never must be `undefined` (never heard of something like that)?

**Comment by thysultan** [comment]
You could use `name in object`, and it will probably still work. hasOwnProperty however won't give some properties are exotic getters/setters that live down the prototype chain.

>Or is the special rule that in custom elements properties never must be undefined.

Normal DOM nodes never have properties that resolve to `undefined` this was the reason behind just using this to check if the property exists.

**Comment by mcjazzyfunky** [comment]
Please have a look at the following demo:
https://codesandbox.io/s/silent-wave-oxk5y?file=/src/index.js

Working as expected in Preact ... not working at all in Dyo (due to the undefined value in the `items` props - see JS console).

**Comment by mcjazzyfunky** [comment]
Another problem is that the naming conventions for attributes and events differ between different web component libraries.
Vaadin web components for example use kebab-case for event names like `selected-item-changed`: This will work in Dyo if you write `<vaadin-combo-box onselected-item-changed=... >` but UI5 web components use camelCase for event names like `headerClick`. As Dyo will just lower-case the event names, it's not possible to use such custom elements directly (of course using `useRef` and `useEffect` will always work - but that's a hell of an overhead, if you do not find a way to automate this).

**Comment by thysultan** [comment]
>Another problem is that the naming conventions for attributes and events differ between different web component libraries.

Yes this is an expected and deliberate caveat. Trying to support all manner of event names is a cost-benefit deliberation. 

>UI5 web components use camelCase for event names like headerClick

Then again i question how `UI5 web components` can work in React if that is the case, as it does the same.

**Comment by thysultan** [comment]
In https://github.com/dyo/dyo/blob/master/src/Interface.js#L221 we could we could add a check for `name in instance` to fix this, i.e

```js
if (current == undefined) {
    if (!(name in instance)) {
        return attribute(name, value, instance)
    }
}
```

and remove the else keyword.

**Comment by mcjazzyfunky** [comment]
> Then again i question how UI5 web components can work in React if that is the case, as it does the same.

Without knowing it, I just guess that you always have to use React wrapper components for custom elements (if I remember correctly, React currently always applies `setAttribute` for all props on custom elements - which will fail for many custom elements, I guess).

> In https://github.com/dyo/dyo/blob/master/src/Interface.js#L221 we could add a check for name in instance to fix this [...]

That sounds great :smiley:

> Yes this is an expected and deliberate caveat. Trying to support all manner of event names is a cost-benefit deliberation.

I can understand this decision, but I guess if someone really wants to use a custom element suite XYZ and those custom elements use event names in camelCase, then that's a show stopper for using Dyo in that project, because I guess nobody wants to write Dyo wrapper components for all the components in the library XYZ.

Please compare the difference between Preact's custom element support and Dyo's regarding event names:
https://codesandbox.io/s/late-leftpad-tbl68

While `<some-component onsome-event=.../>` and `<some-component onsomeEvent=...>` may look a bit odd (frankly, I do not like it at all, optically), at least all event names are working in Preact.

**Comment by thysultan** [comment]
That's understandable.

They way preact supports those events is to assume any function value that starts with `on` but does not have a corresponding `name in Node` reference will be applied with out lowercasing the name, which is an assumption closely linked to the DOM having i.e `onclick` properties for events, something that may not be the case for non-DOM targets which dyo aims to support.

That is to say it will break the normal case `onClick` on none DOM targets, it the target doesn't mimic that DOM heuristic of having event properties in addition.

**Comment by mcjazzyfunky** [comment]
Sorry, I don't get it: This seems to be the place where the lowercasing of the event name is happening. That whole `properties` function looks pretty DOM depending to me, not really target agnostic ...

https://github.com/dyo/dyo/blob/e4a4ec31f0b642875527ca52abb5dcbab515c372/src/Interface.js#L206

Just for information: The counterpart in Preact: https://github.com/preactjs/preact/blob/c317a96f80b93cc31a4e1b81c722221493165491/src/diff/props.js#L99

**Comment by thysultan** [comment]
It is target agnostic. for example:

```js
Dyo.render(h('h1', {class: 'foo'}, 'Text'), {...interface})
```

Where interface is itself and provides methods that return an objects with `createElement`, and have `appendChild`, `removeChild`, `setAttribute` in their [direct/prototype chain](https://github.com/dyo/dyo/blob/e4a4ec31f0b642875527ca52abb5dcbab515c372/src/Interface.js#L12).

Assuming that `onevent` will be present on this object is specific to the DOM, for example i could implement a renderer like:

```js
Dyo.render(h('h1', {class: 'foo'}, 'Text'), {
	createElement() {
		return {
			appendChild() {},
			setAttribute() {},
			removeAttribute() {}
		} 
	},
	get ownerDocument() {
		return this
	}
})
```

The renderer follows that the object returned from `createElement` implement at least `appendChild`, `removeChild`, `setAttribute` and `removeAttribute` methods, and if it has any getter/setters for properties, Dyo will use that instead of `setAttribute`.

**Comment by mcjazzyfunky** [comment]
Okay, thanks, but isn't there at least the possibility to extend  `Interface` itself with a special function to handle event name mapping dependent on event name and `instance` or whatever?
Having a really good support for custom elements is just a too good feature to be neglected.

**Comment by thysultan** [comment]
At the moment no, once it's been lowercased that's what's passed downstream(to the interfaces addEventListener method).

Custom elements with exotic event-NaMes are probably going to be hard to support at the same time as custom interfaces(renderers), it's an either or proposition unless there's a work around that i'm not seeing.

**Comment by mcjazzyfunky** [comment]
Okay thanks.
To come to an end: Would be great if you could employ this `name in instance` fix to support `undefined` prop values. Many thanks. After that, at least those custom elements with lowercase, kebab-case and snake_case naming conventions for events are fully supported by Dyo out of the box.
This is already a big step forward.

**Comment by mcjazzyfunky** [comment]
Just for your information: In the meanwhile the event name convention in the UI5 webcomponents library has changed from camelCase to kebab-case. So UI5 should also work with Dyo out of the box soon.
See [here](https://github.com/SAP/ui5-webcomponents/commit/af1cfbe65725586f97fd0a9182c58b78514d905d#diff-713be0992547cc6ced4d02bd3e24ca08L113).
