### ISSUE TITLE
Real Browser tests with Karma

### ISSUE THREAD

**Issue by Zolmeister** [dyo/dyo#35]
[Karma](https://github.com/karma-runner/karma)
sample karma config:

```coffee
{
  singleRun: true,
  frameworks: ['mocha'],
  files: ['./script/test/index.js'],
  browsers: ['ChromeHeadless']
}
```

**Comment by Zolmeister** [comment]
Also before cutting a release, should be run against all supported real-browsers via [SauceLabs](https://saucelabs.com) ([free](https://saucelabs.com/open-source) for open-source)
See [`karma-sauce-launcher`](https://github.com/karma-runner/karma-sauce-launcher)

**Comment by thysultan** [comment]
Will we be able to run the mocha tests through this or will there be the need to port/duplicate some tests?

**Comment by Zolmeister** [comment]
it will run the mocha tests, though they will need to become isomorphic (run both in browser and node.js)
