### ISSUE TITLE
getSnapshotBeforeUpdate() / getDerivedStateFromProps()

### ISSUE THREAD

**Issue by rosenfeld** [dyo/dyo#55]
It seems like React will deprecate componentWillMount and componentWillUpdate. Are there any plans to support the new hooks getSnapshotBeforeUpdate / getDerivedStateFromProps?

**Comment by thysultan** [comment]
From an implementation perspective there is no reason and thus no plan to remove the`Will` lifecycles methods like React given that they are async safe with regards to the co-operative scheduling rendering i hope to implement. 

That said i'm skeptical of the value the new lifecycle methods pose(apart from compatibility) since they also introduce their own set of quirks, so at this stage the preference is to observe the different patterns and quirks that arise from these lifecycles between now and the time that the `Will` lifecycles are planned for removal/depreciation.

**Comment by rosenfeld** [comment]
I understand, but I'm particularly concerned about compatibility exactly. I want to be able to switch my code to use Inferno or React any time, or to perform some comparisons from time to time. I don't want to write new code relying on some React API that has been deprecated because I'd have to rewrite it at some point.

**Comment by thysultan** [comment]
The `Will` lifecycles have yet to be deprecated. I would don't want to implement them without the afore-mentioned perspective on patterns/quirks that manifest between now and then(if and when they are depreciated).

**Comment by rosenfeld** [comment]
Well, the fact that they have renamed it to prefix them with UNSAFE_, and the fact that they proactively recommend against using them, I'd say the effect is the same. One shouldn't use them for new written code. At least this was my understanding reading the documentation. I'm not asking you to deprecate them, just to consider adding the new ones in order to keep compatibility with React.

**Comment by thysultan** [comment]
I am considering them for a 9.x release but not the immediate upcoming 9.0.0 release for the above mentioned reasons.

**Comment by rosenfeld** [comment]
So that you know, my intention was to replace componentWillUpdate with getSnapshotBeforeUpdate but once I noticed that the latter is only called after render then I no longer have a real use case for getSnapshotBeforeUpdate. However, I understand I could use getDerivedStateFromProps instead. At first, by looking at its name, it seemed like it would only make sense when props were changed, which wasn't the case, but now I see I can also get the previous and current state by using it even when only the state has changed. However, this is not equivalent to componentWillUpdate because shouldComponentUpdate might return false, so there's no guarantee of a following render() call. It's unfortunate that it will no longer be guaranteed to work with React after version 17.

Particularly I'm implementing some sort of state machine, so it's important to watch for changes to an specific state, named "action". When the action is changed, I'd like to reset some state. Currently the way I implement that is by storing the previous action during render. Then I compare the current action state to the previous one. If it changes, then I'd modify some of the states that should be reset in-place since it's too late to call setState from render. If you're aware of a cleaner approch to that problem I'd love to hear it.

I was thinking about comparing the previous and current action in getDerivedStateFromProps, but the problem is that I should assume shouldComponentUpdate would always return true when the action changes. Otherwise I might reset some state inadvertently in case rendering would be cancelled by shouldComponentUpdate returning false. On the other hand, maybe it doesn't make sense for shouldComponentUpdate to return false after changing the "action" state. I'm still considering that option...

**Comment by thysultan** [comment]
React 16.3 doesn't call `getDerivedStateFromProps` for state changes, the static method is called when there are new props in addition to its mount invocation. That is to say – `getDerivedStateFromProps` would be called even when `shouldComponentUpdate` returns false similar to how `componentWillReceiveProps` would be called before the `shouldComponentUpdate` lifecycle method.

If i'm not mistaken all `*Will` methods that React intends to remove in version 17 next year will still remain in the form of prefixed `UNSAFE_*Will` variants.

There are other caveats associated with `getDerivedStateFromProps` being a static method that has no access to `this`, previous props or previous state, some of which are mentioned in [https://github.com/reactjs/rfcs/pull/40](https://github.com/reactjs/rfcs/pull/40). I'd recommend contributing your use case to the discussion going on there.

**Comment by rosenfeld** [comment]
@bvaughn what @thysultan said is that the UNSAFE variants have not been deprecated yet and no plans have been disclosed to do that yet.

@thysultan the fact that those new members are static ones is already enough for me to not use them as I don't see fit. Honestly I think the React team is going in the wrong direction, but maybe I'm just wrong...

**Comment by rosenfeld** [comment]
I'm not sure the React's issues is the best place to discuss something like that, but if you're curious, I just created an issue there in an attempt to discuss this use case: https://github.com/reactjs/reactjs.org/issues/781

**Comment by bvaughn** [comment]
> @bvaughn what @thysultan said is that the UNSAFE variants have not been deprecated yet and no plans have been disclosed to do that yet.

Eh, the comment I was replying to said, "_The Will lifecycles have yet to be deprecated. I would don't want to implement them without the afore-mentioned perspective on patterns/quirks that manifest between now and then(**if and when they are depreciated**)._"

Seemed worth clarifying that the plans for deprecating those methods are solid, and outline in the blog post I linked to.

**Comment by rosenfeld** [comment]
Oh, sorry, now I understand the confusion. I think he meant that even though they have been renamed, they have not yet been deprecated in the UNSAFE variant version. Just the old name has been deprecated so far.
