### ISSUE TITLE
Integration with react-dev-tools Chrome extension

### ISSUE THREAD

**Issue by rosenfeld** [dyo/dyo#70]
Hi, this is just an idea and feel free to ignore it, but if Dio.js was able to integrate to react-dev-tools in development mode that could add a boost to the developer's productivity. Inferno.js does provide a package to perform this integration which you could inspect here to evaluate whether it would worth creating something similar for Dio.js:

https://github.com/infernojs/inferno/blob/master/packages/inferno-devtools/src/bridge.ts

**Comment by thysultan** [comment]
Sure, do you want to try porting that and see how it goes?

**Comment by rosenfeld** [comment]
I'd certainly love to try that but I had to just pass an oportunity to get some good money writing some articles because of the current project I'm working on. I don't think I'll have time to work on this at least for the next 6 months as we're in a very early stage and on a small budget so I'm trying to deliver as much as possible to see if we can get some clients which would allow me some more free time hopefully. I'll let you know once I get some free time to try integrating with react-dev-tools but it won't be any time soon so feel free to close this issue for now and I'll reopen it with a pull request when I find some time to work on it. Thanks.
