### ISSUE TITLE
Enhance build scripts to produce development and production packages

### ISSUE THREAD

**Issue by mcjazzyfunky** [dyo/dyo#72]
**Description**:
As discussed in #71 it would be nice if  the DIO build scripts produced both development and production artifacts for the usual DIO packages.
This would allow (for future DIO versions) additional checks and validations in development mode to increase the overall development experience, while those additional checks and validations would not be applied in production mode (for performance reasons).
This is similar to React, where you find two packages "react.development.js" and "react.production.min.js".

**Task**:
Enhance DIO's build scripts to produce packages for development and production. Find some way to allow code blocks to be removed for the production artifacts.

**Comment by mcjazzyfunky** [comment]
@thysultan Could you please tell me, what naming conventions your prefer for the built artifacts?

For example, those file names are used in my current implementation, but of course I can change the names as you like:

-rw-r--r-- 1 owner 197121 14K Jul 25 09:34 cjs.development.js
-rw-r--r-- 1 owner 197121 14K Jul 25 09:34 cjs.production.js
-rw-r--r-- 1 owner 197121 99K Jul 25 09:34 esm.development.js
-rw-r--r-- 1 owner 197121 25K Jul 25 09:34 esm.development.min.js
-rw-r--r-- 1 owner 197121 44K Jul 25 09:34 esm.development.min.js.map
-rw-r--r-- 1 owner 197121 99K Jul 25 09:34 esm.production.js
-rw-r--r-- 1 owner 197121 25K Jul 25 09:34 esm.production.min.js
-rw-r--r-- 1 owner 197121 44K Jul 25 09:34 esm.production.min.js.map
-rw-r--r-- 1 owner 197121 99K Jul 25 09:34 umd.development.js
-rw-r--r-- 1 owner 197121 24K Jul 25 09:34 umd.development.min.js
-rw-r--r-- 1 owner 197121 43K Jul 25 09:34 umd.development.min.js.map
-rw-r--r-- 1 owner 197121 99K Jul 25 09:34 umd.production.js
-rw-r--r-- 1 owner 197121 24K Jul 25 09:34 umd.production.min.js
-rw-r--r-- 1 owner 197121 43K Jul 25 09:34 umd.production.min.js.map

**Comment by thysultan** [comment]
dio.esm.production.js etc... 

I pushed a [rollup-ify](https://github.com/thysultan/dio.js/tree/rollup-ify) branch that i had locally from past efforts on this in case that might help.

**Comment by mcjazzyfunky** [comment]
@thysultan I would suggest do use special comments to mark code blocks that shall be stripped depending on "DEVELOPMENT vs PRODUCTION". It's done differently in React/Webpack (=> process.env.NODE_ENV), but DIO's build scripts do not use Webpack.

```javascript
  // DEVELOPMENT:start     				
 console.log('THIS IS DEVELOPMENT')
  // DEVELOPMENT:end
  // PRODUCTION:start
  console.log('THIS IS PRODUCTION')
  // PRODUCTION:end
```

Is that okay for you or do you prefer an other solution or syntax?

**Comment by Zolmeister** [comment]
do a string-replace on `process.env.NODE_ENV` and UglifyJS will clean it up

**Comment by mcjazzyfunky** [comment]
@Zolmeister Thanks for your suggestion.
Mmmh, but UglifyJS is currently only used for the "*.min.js" packages, those files that are not minified do not use UglifyJS.

**Comment by Zolmeister** [comment]
@mcjazzyfunky I simply meant it in-lines the conditional (so avoids including unnecessary code in `.production.min.js`)

e.g.

```js
if (process.env.NODE_ENV === 'development') {
  console.log('debug string')
}
if (process.env.NODE_ENV === 'production') {
  console.log('production string')
}
```

becomes

```js
if ('production' === 'development') {
  console.log('debug string')
}
if ('production' === 'production') {
  console.log('production string')
}
```

which work for both production and development.
However you don't want the `.min.js` to contain debug string`, but this isn't a problem because UglifyJS will omit the entire branch

```js
console.log('production string')
```

**Comment by mcjazzyfunky** [comment]
Thanks again @Zolmeister ... now I get it ;-)
Okay, I'll implement it the way you've suggested ... @thysultan gave "Thumbs up"...

**Comment by mcjazzyfunky** [comment]
@thysultan I've started to modify the "script/build/index.js" scripts before I've opened this issue.
So 6 days ago I did not know that maybe you prefer to use "rollup.js" to completely replace the build scripts.

Could you please tell what solution exactly you perfer to split the build results into DEV/PROD?

Option 1: Shall I just modify the original build scripts WITHOUT switching to "rollup.js" ... this does not seem to be a big deal => please see this preversion which seems to do the job basically (there are also some minor changes in some other files): http://www.mergely.com/tlx582Gs (script/build/index.js)

Option 2: Shall I switch to "rollup.js", add the "DEV/PROD" split there and replace the "script/build" scripts completely? This is of course more complicated and therefore I would need a bit more detailed task description from you.

Option 3: Something completely different ...

**Comment by mcjazzyfunky** [comment]
@thysultan Could you please invite me as collaborator for DIO? ... so that I can create a new branch "issue72" ... thanks.

**Comment by mcjazzyfunky** [comment]
@thysultan 

Two questions:

1. The "dist" directory is currently not listed in ".gitignore" - shall this stay as is or shall "dist" be added to ".gitignore"?
FYI: Current sum of file sizes in directory "dist" (branch "issue72") : 748k

2. May I commit "packages-lock.json"? (npm  >= v5: See "This file is intended to be committed into source repositories", to be read here: https://github.com/npm/npm/blob/v5.0.0/doc/files/package-lock.json.md)

**Comment by thysultan** [comment]
Lets add that to `.gitignore`. It would reduce some of the noise in diffs. With that change we'd need to run build before tests.

Haven't had the best experience with "packages-lock.json" so i'm biased to not include it. If we can add that to `.gitignore` that would be great.

**Comment by thysultan** [comment]
@mcjazzyfunky Done.

**Comment by thysultan** [comment]
1) You could use `/* istanbul ignore next */` in the script that replaces process.env.NODE_ENV... or

2) Further reduce the dist artefacts to just `.production.js` and `.development.js` like [React](https://unpkg.com/react@16.4.2/umd/), where `.production.js` is the final minified output.

**Comment by mcjazzyfunky** [comment]
@thysultan Thanks for your answer.
I do not mind adding ```/* istanbul ignore next */```  explicitly in the source code, but  what I do mind is that this may "fake" the test coverage statistics (adding it implicitly would make things even worse, I think).
Running the unit tests on a minified production package will result in hardly readable lcov reports (as far as I know istanbul does not support map files).
To make a long story short: I think for now I will just stick with the explicit ```/* instanbul ignore next */``` solution - it's not really nice nor smart but it does it's job and maybe we can find a better solution when DIOs build scripts switch to rollup or webpack or whatever somewhere in the future.

**Comment by thysultan** [comment]
@mcjazzyfunky Was there a reason `istanbul` did not report the mentioned functions? I'd assume the build that contains this should have had the specified branch accounted with the tests.

**Comment by mcjazzyfunky** [comment]
In the latest version of branch "issue76" the "/* istanbul ignore next */" comments are removed from file "PropTypes.js" => instead the build script "script/build/index.js" now has an array "devOnlyCoreFiles" to declare files to be "development exclusive".
Yet, the "istanbul ignore" comment is still needed here (=> Element.js):

```javascript
  /* istanbul ignore next */
  if (process.env.NODE_ENV === 'development')
      checkPropTypes(type, props)
```
