### ISSUE TITLE
<input type="checkbox" checked={ undefined } defaultChecked={ true } />

### ISSUE THREAD

**Issue by rosenfeld** [dyo/dyo#75]
The checkbox in the title is rendered unchecked in Dio.js and checked in React.

MUICSS creates a wrapper over the checkbox, rendering it like `<input type="checkbox" checked={ props.checked } defaultChecked={ props.defaultChecked } />`.

Could you please make Dio.js behave like in React?

**Comment by thysultan** [comment]
Can you link to the repro you had for this here.

**Comment by rosenfeld** [comment]
[note: I've updated the link in the previous comment] If you're accessing the link directly from the notifications by e-mail, here you are: https://codesandbox.io/s/x9997158pp (CodeSandbox has its own bugs that will prevent me to update the code sometimes)
