### ISSUE TITLE
ForwardRefs do not support defaultProps in DIO while in React they do

### ISSUE THREAD

**Issue by mcjazzyfunky** [dyo/dyo#81]
It would be nice if forwardRefs would support defaultProps as in React.

See the follwing demo:
https://jsfiddle.net/pr3gnsuj/

**Comment by mcjazzyfunky** [comment]
I'll have a look a this => assigned issue to myself

**Comment by mcjazzyfunky** [comment]
@thysultan I've evaluated that: It's basically for the same reason why forwardRefs do also not support propTypes yet (in branch issue76). It's three lines of code (plus unit tests). I'll fix that together with the "propType support for forwardRefs bug" in branch issue76, so there will not be a extra pull request for #81.

**Comment by thysultan** [comment]
Yes, this is also related to Context, if we returned functions from those functions it would resolve itself.

**Comment by mcjazzyfunky** [comment]
Bugfix can  be found here (branch "issue76"):

https://github.com/thysultan/dio.js/commit/d0ade83120ecfe0ea8f44fc1e2086a78419f05fe#diff-a6b77a6eb2476ebcc9cb30d1be3aaa2aL523

Two new unit tests can be found here (branch "issue76"):

https://github.com/thysultan/dio.js/commit/d0ade83120ecfe0ea8f44fc1e2086a78419f05fe#diff-cafcab72d15b5e55864154c33e3fec14R660
