### ISSUE TITLE
Server rendering v0.0.18

### ISSUE THREAD

**Issue by Zolmeister** [dyo/dyo#86]
if `h` doesn't come from the server package, I get `n.then is not a function` (presumably failing the Symbol() check)

```coffee
{h, render} = require 'dyo/server/dist/dyo.umd.js'
# {h} = require 'dyo' 
```

Additionally `componentDidMount` should not be called server-side (https://github.com/dyo/dyo/blob/master/test/server/Serialize.js#L36), only `componentWillMount` should be called. (see https://github.com/dyo/dyo/issues/48)

**Comment by thysultan** [comment]
The first one seems like a bug.

The second is intended and equally applies to `componentDidCatch`. This reduces the friction for more isomorphic components with regards to fetching data.

**Comment by Zolmeister** [comment]
I don't know about `componentDidCatch`, but I'm pretty sure [React](https://reactjs.org/docs/react-component.html#componentdidmount) does not call `componentDidMount` server-side.

`componentDidMount` is specifically used when directly accessing DOM elements, not for fetching data. That probably belongs in the constructor

**Comment by thysultan** [comment]
Should we apply the same logic to `componentDidCatch` or special case that and allow it on the server(or non client mountable environments).

**Comment by Zolmeister** [comment]
I can confirm React doesn't call [`componentDidCatch`](https://reactjs.org/docs/error-boundaries.html) server-side, so I'd say follow their pattern and also not call it
