### ISSUE TITLE
Invalid handling of ref objects (branch 'hooks')

### ISSUE THREAD

**Issue by mcjazzyfunky** [dyo/dyo#90]
[Edit: The initial issue description was wrong => description has been updated]

The `current` property of ref objects will not be set to `null` when the referred DOM elements are unmounted.

Please see the correct behavior in DIO and React here and the wrong behavior in Dyo here (please open JS console):

DIO: https://jsfiddle.net/73opa4fm/
React: https://jsfiddle.net/ovthf68L/
Dyo: https://jsfiddle.net/zvqa607h/

**Comment by thysultan** [comment]
There aren't function refs in that branch only `useRef`.

**Comment by thysultan** [comment]
But we should probably do the same for `useRef` objects with `obj.current = null`

**Comment by mcjazzyfunky** [comment]
What do you mean by
> There aren't function refs in that branch(hooks), only `useRef`

?

In my demo I use something like:

`<ComponentA ref={callback}/>`

and this callback is invoked when the component is mounted but not when it is unmounted.
I have not checked for `{ current: ... }` ref objects and did not use `useRef`. Maybe its the same issue there.

**Comment by mcjazzyfunky** [comment]
Ooops, sorry, I think I made a mistake: In my demo I've used my own implementation of `useImperativeHandle`, which seems to be buggy.

Yes, you are right we should do the same with `useRef`. I will check again tomorrow.
.... to be continued ....

**Comment by mcjazzyfunky** [comment]
@thysultan 
Nevertheless there is something wrong with ref callbacks on normal DOM elements => I've updated the issue description above.
Would it be possible to publish an alpha version of the "hooks" branch on npmjs.com?
It would be easier to provide demos then.

**Comment by thysultan** [comment]
Yes, only ref objects.

>Would it be possible to publish an alpha version of the "hooks" branch on npmjs.com

Done. Dyo@0.0.19

**Comment by mcjazzyfunky** [comment]
@thysultan Thank you very much for the information and the publishing of Dyo.
I've updated the issue description and title accordingly.
You'll find a little Dyo demo linked in the description that shows the wrong behavior.

**Comment by thysultan** [comment]
@mcjazzyfunky Dyo@0.0.20 should have a patch for that. Thanks.

**Comment by mcjazzyfunky** [comment]
Great. Thanks a lot. My simple demo is working now.
I'll close this issue.
