### ISSUE TITLE
Hydrate API

### ISSUE THREAD

**Issue by Zolmeister** [dyo/dyo#94]
Missing [`hydrate`](https://reactjs.org/docs/react-dom.html#hydrate) api

e.g.
```coffee
    $el.innerHTML = '<img src="x" onerror="console.log(111)">'

    X = ->
      h 'img',
        src: 'x'
        onerror: -> console.log 111

    # render(X, $el)
     hydrate(X, $el)
```
should only log once, because the only DOM modification should be `onerror` attribute

**Comment by Zolmeister** [comment]
@thysultan any chance for this?

**Comment by thysultan** [comment]
This was intentional, in trying to move away from dual entry points and only have `render` become the central entry point for rendering both on the client and server, especially since the client render can bootup to first render fast without hydration.

**Comment by Zolmeister** [comment]
This API is required for full-page server-side rendering.
My root component looks like this:

```coffeescript
app = ->
  [
    h 'head',
      h 'script', {src: '/bundle.js'}
    h 'body',
      h 'div', 'test'
  ]
```

Without `hydrate()`, `bundle.js` will be requested twice.

**Comment by Zolmeister** [comment]
I no longer think this is necessary
