### ISSUE TITLE
Are props dependent hook functions really a good idea?

### ISSUE THREAD

**Issue by mcjazzyfunky** [dyo/dyo#95]
Other than in React, in Dyo there are some built-in hook functions that depend on `props` (at least more or less, depending on usage) :

- `useState(props => ...)`
- `useRef(props => ...)`
- `useResource(props => ...)`
- `useReducer(..., props => ...)` [Edited much later: I was wrong with the following comment, please ignore] ~~// I don't think that in the current implementation this is really working, but at least the API documentation says so.~~

Do you really think this is a good idea?
Doesn't it make things just needlessly complicated, without a real win?
For example, the TS types of the above mentioned built-in hook functions will be much more complicated than actually necessary.

**Comment by Zolmeister** [comment]
I think it's genius. It is both more correct (in terms of functional purity) and explicit (using object deconstruction).

e.g.

```js
function Component() {
  [size] = useState({width, height}) => width * height)
  [color] = useState({baseColor, tint} => colorMixer(baseColor, tint))
}
```

It's clear exactly which props are depended on by each hook

**Comment by mcjazzyfunky** [comment]
@Zolmeister Thanks for your response.

But what if you are using default properties in the above example and you only want to declare them once. Wouldn't you do something like the following?

```javascript
function Component({ width = 100, height = 100, baseColor = 'grey', tint = 'whatever' }) {
  const
    [size, ...] = useState(width * height), // or () => width * height if you prefer
    [color, ...] = useState(() => colorMixer(baseColor, tint))

  // using width, height, baseColor, tint also somewhere below here...
  // [...]
}
```

Also, I think that things are getting a bit ugly if someone is using that `useState(props => ... )` API somewhere in custom hooks - feels like a complete anti-pattern, at least I cannot think of one single use-case where using `useState(props => ...)` inside of a custom hook could make any sense.

**Comment by Zolmeister** [comment]
@mcjazzyfunky
A 'pure' solution might look like this (which as you mentioned has an inherent syntactic cost):

```js
function Component ({width = defaultWidth = 100, height = defaultHeight = 100}) {
  [size] = useState(({width = defaultWidth, height = defaultHeight}) => compute(width * height))
}
```

But maybe a combination is optimal. No longer as 'pure', but still provides some logical isolation.

```js
function Component ({width = 100, height = 100}) {
  [size] = useState(({scale}) => compute(width * height * scale))
}
```

There is perhaps a non-trivial cost to isolating props in being able to reference a single-point-of-truth for interface documentation, though maybe that can be solved another way (e.g. JSDoc).

True that no hook would ever declare it's own `props => ...` callback, but I could see custom hooks re-exposing the interface for consumption. e.g.

```js
function useMySize(initialSize) {
  [size, setSize] = useState(initialSize)
  useEffect(_=> setSize((prevSize) => prevSize + 1))
  if (size > 10) return 10
  return size
}

function Component() {
  size = useMySize(({width, height}) => compute(width * height))
}
```

**Comment by thysultan** [comment]
They aren't dependent on props, props are an optional argument passed to the function. You can use them like you would their React counter-parts that is – as though the argument was not passed. They do however afford you some leeway in certain cases.

```js
const calcArea = ({width, height}) => width * height
const useArea = () => useState(calcArea)
const Example = (props) => { useArea() }
```

Instead of

```js
const useArea = (width, height) => useState(() => width * height)
const Example = ({width, height}) => { useArea(width, height) }
```

In the second example you would always destruct the `width, height` from props while in the first
you will only do this when initialising the state value and can avoid inline functions when that makes sense. 

>I don't think that in the current implementation this is really working, but at least the API documentation says so.

I should work in its current form. Did you come across a bug?

**Comment by mcjazzyfunky** [comment]
> They aren't dependent on props [....]

Actually, in Dyo they DO depend on props (even if this variant is optional):

```ts
// Dyo (simplified, not 100% correct):
function useState<T, P = {}>(init: T | ((props: P) => T)): ...
```
vs.

```ts
// React (simplified, not 100% correct):
function useState<T>(init: T | (() => T)): ...
```

Anyway, I still cannot see the big win .... I can only see:
- complicated function types
- less automatic type inference
- it's possible in Dyo to implement two (bad designed) custom hooks that are NOT combinable (I think in React each custom hook is theoretically combinable with any other hook, isn't it?) 

Anyway, like I always say, it's perfectly fine to have different opinons about a subject. So thank you very much for your responses. I will close this issue then.

PS:

> I don't think that in the current implementation this is really working, but at least the API documentation says so.

My bad, I was wrong with this. I've tested it again tonight and everything worked fine. Nothing to do here.

**Comment by thysultan** [comment]
>Actually, in Dyo they DO depend on props (even if this variant is optional):

If you omit their use nothing will change, you can use `useState` and friends like you would in React without making use of the props argument passed to function initialisers.

Are you writing typescript typings?

```js
function useState<T, P = {}>(init: T | ((props?: P) => T)): 
```

>it's possible in Dyo to implement two (bad designed) custom hooks that are NOT combinable

Do you have an example of this?

**Comment by Zolmeister** [comment]
This example illustrates the poor composability mentioned by @mcjazzyfunky: https://github.com/dyo/dyo/issues/95#issuecomment-515077568
A more composable version would be:
```js
const calcArea = ({width, height}) => width * height
const useArea = (getInitialArea) => useState(getInitialArea)
const Example = (props) => { useArea(calcArea) }
```

Because the callback is only ever called for initial values, the logical separation from 'normal props' (which update) might be valuable.

Examples:

```coffee
Input = ({value, onValue}) ->
  [value, setValue] = useState value

  z 'input',
    value: value
    oninput: (e) ->
      onValue e.value
      setValue e.value

Input = ({onValue}) ->
  [value, setValue] = useState ({value}) -> value

  z 'input',
    value: value
    oninput: (e) ->
      onValue e.value
      setValue e.value
```

The 'better' version is still not immediately obvious to me. I think a larger project would better illustrate the differences and allow more complete analysis. I do think it's at least interesting enough to keep in the API for now (though I don't use typescript).

(Unrelated, I dislike `useMemo` becoming a no-op if the last argument is omitted. I think it should be equivalent to `[]`. But this matches React, so I won't open an issue)

**Comment by mcjazzyfunky** [comment]
Again, I do not want to waste somebody's time ... just to answer the above questions:

Regarding non-composability of badly designed custom hooks in Dyo:

If custom hook functions depend on special shape/struct of props then their types will look something like (and I think this is in most cases an example of bad design in custom hook implementation):

```ts
function useCustom1<..., P extends P1>(...): ....
function useCustom2<..., P extends P2>(...): ....
```

If P1 and P2 are not compatible then `useCustom1` and `useCustom2` are not composable or at least composition might be kinda tough.

For example if:

```ts
type P1 = { width: integer, height: integer }
type P2 = { w: integer, h: integer }
```
or

```ts
type P1 = { width: integer, height: integer }
type P2 = { width: string, height: string }  // something like '100px', '100pt', '100em'
```

Also if you have a Dyo third-party custom hook function that depends on a special props structure (again: bad design!) and you want to use it in your component then you can only really use it if the props type of your own component is compatible with the one necessary for the third-party custom hook.

**You will NEVER have the above composability issues in React as it simply does not allow that custom hooks require a special props structure.**

A while ago, Dan Abramov has written a comment to some guy's API proposal where that guy has suggested to pass `props` as argument to the callback in `useEffects` (it's not exactly the same as in Dyo's `useState` etc. but the patterns are similar).

> In your proposed design, props becomes an argument of useEffect callback. Perhaps I misunderstood how that works. But it seems like this breaks encapsulation quite a bit because any custom Hook now suddenly has access to its owner component's props. That makes them non-compositional. One Hook could read props (assuming specific ones exist), and then later you might change the component to not receive that prop. Or you might lift a Hook out of a component, and the Hook will break. There's no obvious way that you'd know to update the custom Hook to not depend on it.

I'm really a big fan of Antoine de Saint Exupéry's wise sentence:

> "Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away".

For API design this sentence may not be 100% applicable, as not really necessary "API sugar" is often fine if it makes the use of the API much easier (really MUCH easier) .

I just have the feeling that this "props as argument for the callback function" thingy can easily be taken away, things are not really much easier with it (maybe just more confusing => personal opinion of course ;-) ).

---

Regarding the fact that this "props as argument for the callback function" thing makes it sometimes easier to reduce the number of closures defined in the function body (as maybe someone is worried that too many closures defined in the function body could trouble the garbage collector):

Something like:

```ts
function initState({ prop1, prop2 }) {
  return calcState(prop1, prop2)
}

function MyComponent() {
  ... = useState(initState) 
}
```

can at least be replaced (trivially/naively) by:

```ts
function MyComponent({ prop1, prop2 }) {
  ... = useState(calcState.bind(null, prop1, prop2))
}
```

Here `calcState.bind(...)` will of course often create temporary functions that may never really be used, but this will surely not be a problem for the garbage collector.

---

> Are you writing typescript typings?

No, I'm not ... but I'm quite sure someday somebody will do so ... would be a pity if not :smiley:
