### ISSUE TITLE
Feature request: Add useValue hook.

### ISSUE THREAD

**Issue by vuhg** [dyo/dyo#98]
Hi @thysultan,

I super like `dyo` since it supports async from the core. And i am experimenting some ideas with dyo.

I wonder if we have useValue as following:

```javascript
// signature
type ValueComparator<T> = (oldVal: T, newVal: T) => boolean
type ValueUpdater<T> = (oldVal: T) => T
type ValueGetSet<T> = (valOrFun: T | ValueUpdater<T> | undefined) => T | void
type useValue<T> = (val: T, comparator: ValueComparator<T>) => ValueGetSet<T>

// usage
const count = useValue<number>(
  0, 
  (oldVal: number, newVal: number) => newVal - oldVal >= 2
);

<p>Counter = { count() } </p>
// will not update
<button onclick={() => count(c => c + 1)}> ++ </button>
// will update
<button onclick={() => count(c => c + 2)}> +++ </button>
// update one time 
<button onclick={() => count(10)}> 10 </button>
```

I think that `useValue` is more single like source of the truth than `useState`.
Instead of passing `[state, setState]` around, you only pass `value`.
With component composition, we usually pass `state` and `setState` separately.
It is easy confusing if those component is in separate files.

With just single `value`, it is much clearer. Also it is easy to search.
(As I am not good with regex).

Currently i implement as following and import everywhere:
```javascript
function useValue(val, comparator = Object.is) {
  const [value, setValue] = useState(val);

  function getOrSet(valOrFun) {
    if (arguments.length) {
      const val = typeof valOrFun === "function" ? valOrFun(value) : valOrFun;
      if (comparator(value, val)) return;
      setValue(arguments[0]);
    } else {
      return value;
    }
  }

  return useCallback(getOrSet);
}
```

I can do PR if you accept.

Thank you for making `dyo`, thysultan.

**Comment by vuhg** [comment]
I think `val` can be lazy initialized.
```javascript
type useValue<T> = (val: T | () => T, comparator: ValueComparator<T>) => ValueGetSet<T>
```

**Comment by vuhg** [comment]
@Zolmeister, Thank you for the link. 
Unfortunately, that issue close long time ago.

I think we should be flexible instead of forcing useState for all situation. From thysultan's quote:
>The use of a single setter/getter stream instead of a tuple. So value = use(value) instead of [value, setValue] = use(value). This allows us to use live values to avoid the age old problem of stale data. That is value() would always return the current value.

That would be really great to have `useValue` for different use-cases, patterns.

**Comment by Zolmeister** [comment]
I'd argue it's an anti-pattern https://github.com/dyo/dyo/issues/87#issuecomment-451938453

**Comment by vuhg** [comment]
Hmm, I would ague otherwise.
There is no bad or good or anti pattern. It depends on the use-cases and the dev who uses it.
`state, setState` are not single source of the truth. Just a single `value` are.

Like you have the lightbulb switch, only you can toggle it (`value`). If you and me can toggle the switch through an app (`setState`). Now it is confusing. We have another step is to report who toggled it.

How you implement an simple use-case below:
- With useValue
```javascript
// useField
interface FormField<T> {
 value: ValueGetSet<T>;
 valid: ValueGetSet<boolean>;
 dirty: ValueGetSet<boolean>;
 touched: ValueGetSet<boolean>;
}

function useField({ initialValue, inputRef, pattern, validator }): FormField {

}
```

- With setState???
```javascript
// useField
interface FormField<T> {
 value: T;
 setValue: Function;
 isValid: boolean;
 setIsValid: Function;
 isDirty: boolean;
 setIsDirty: Function;
 isTouched: boolean;
 setIsTouched: Function;
}

function useField<T>({ initialValue, inputRef, pattern, validator }): FormField<T> {

}
```

**Comment by Zolmeister** [comment]
There are measurable costs to abstractions, and while there may be a valid use case it does not imply that a general-purpose library (like Dyo) should provide it.

Your example has nothing to do with hooks.

```js
myForm = new FormField({initialValue: 123})
myForm.value() // 123
myForm.value(456)
```

vs

```js
myForm = new FormField({initialValue: 123})
myForm.getValue() // 123
myForm.setValue(456)
```

or perhaps using es6 getters/setters

```js
myForm = new FormField({initialValue: 123})
myForm.value // 123
myForm.value = 456
```

usage within a component would be

```js
myForm = useMemo(_=>new FormField({initialValue: 123}), [])
```

**Comment by vuhg** [comment]
So you like to add abstractions to user-land code over and over instead of adding small utility to library?
Shouldn't `general-purpose library` should provide functions to user-land?
General-purpose library only provides `useState` for `state, setState` use-cases?

**Comment by Zolmeister** [comment]
I was addressing the meta-critique of 'do anti-patterns exist' by rephrasing my position as utility maximization. I do not believe this feature warrants addition because it should rarely be used.

**Comment by vuhg** [comment]
You just make statement without address my questions.
I don't see how you add value to this request, so i will ignore you in this issue.

I'm waiting for thysultan's or others's ideas.

**Comment by Zolmeister** [comment]
no @vuhg, the correct response is "Thank you for your feedback"

**Comment by thysultan** [comment]
We [discussed](https://github.com/dyo/dyo/issues/87) this previously and decided to not go that route. Like `useImperativeHandle` this can be a custom hook outside of the standard hooks dyo ships with.

```js
function useValue (value) {
  return useMemo(state => {
    return function (value) {
      return arguments.length ? typeof value === 'function' ? value(state[0]) : state[1](value) : value
    }
  }, useState(value))
}
```

**Comment by vuhg** [comment]
Thanks thysultan!

Too bad, i can't use `dyo`.
